"""Derive retrieval_eval_v3: the provenance-valid subset of v2.

v2 is NOT modified and NOT deleted. Its committed report records what was measured
against it at the time, and that record stays true only if the artefact behind it
stays as it was.

v3 exists because 12 of v2's 52 queries can no longer resolve in production: they
reach 42 CFR 410.61 through `ENGINEERING_INFERRED` links, which production
resolution now refuses. A query that cannot resolve measures nothing, and leaving it
in the denominator would understate every rate for a reason that has nothing to do
with retrieval.

**Selection is on PROVENANCE, not on results.** The audit runs before any arm does,
and no query is dropped for scoring badly. Every exclusion is recorded with its
reason, so the difference between v2 and v3 is inspectable rather than asserted.

Do NOT restore the inferred links to recover those queries. The links are refused
for a reason - applicability from resemblance is what ADR-004 exists to prevent -
and reinstating them to make an evaluation look better would be exactly backwards.

    uv run python scripts/build_retrieval_v3.py --write
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parents[1]
V2 = REPO / "eval/datasets/retrieval_v2/questions.yaml"
PROVENANCE = REPO / "data/review/evaluation_provenance.json"
OUT_DIR = REPO / "eval/datasets/retrieval_v3"

HEADER = """\
# Retrieval ground truth, version 3. DERIVED from v2 by provenance, not by hand.
#
# Generated by scripts/build_retrieval_v3.py. Do not edit: regenerate.
#
# WHY v3 EXISTS
#
# Phase 6 made ENGINEERING_INFERRED code links inadmissible for production
# resolution - applicability may not rest on resemblance (ADR-004). 42 CFR 410.61
# was reachable only through two such links, so every v2 query targeting it now
# fails resolution in production. A query that cannot resolve measures nothing, and
# leaving it in the denominator understates every rate for a reason unrelated to
# retrieval.
#
# v2 IS NOT MODIFIED. Its committed report records what was measured against it,
# and that record stays true only while the artefact behind it does.
#
# WHAT WAS EXCLUDED, AND ON WHAT BASIS
#
# Provenance, computed by scripts/audit_evaluation_provenance.py BEFORE any arm was
# run. No query was dropped for scoring badly. Every exclusion is listed below with
# its reason.
#
# WHAT THIS SET HAS NOT ESTABLISHED
#
# It has never been scored. No report exists for it, and no number from v2's report
# may be attributed to it - the denominators differ. Whether and how to re-measure
# is OD-28, and that decision belongs BEFORE the run, not after seeing which set
# produces better figures.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    spec = yaml.safe_load(V2.read_text(encoding="utf-8"))
    audit = json.loads(PROVENANCE.read_text(encoding="utf-8"))["sets"]["retrieval_v2"]
    verdicts = {entry["id"]: entry for entry in audit["entries"]}

    kept: list[dict[str, Any]] = []
    excluded: list[dict[str, Any]] = []
    for question in spec["questions"]:
        verdict = verdicts[question["id"]]
        if verdict["classification"].startswith("VALID"):
            kept.append(question)
        else:
            excluded.append(
                {
                    "id": question["id"],
                    "category": question.get("category"),
                    "classification": verdict["classification"],
                    "intended_policy": verdict["chain"]["intended_policy"],
                    "reason": verdict["reasons"][0] if verdict["reasons"] else "",
                }
            )

    derived = {
        "version": "3",
        "derived_from": "eval/datasets/retrieval_v2/questions.yaml",
        "derived_at": datetime.now(UTC).strftime("%Y-%m-%d"),
        "selection_basis": (
            "provenance only, computed before any arm was run; no query was dropped "
            "for scoring badly"
        ),
        "corpus": spec["corpus"],
        "corpus_kind": spec["corpus_kind"],
        "corpus_source": spec["corpus_source"],
        "criteria_inventory": spec["criteria_inventory"],
        "authored_by": spec["authored_by"],
        "authored_by_role": spec["authored_by_role"],
        "relevance_labels": spec["relevance_labels"],
        "scored": False,
        "scoring_note": (
            "This set has NEVER been scored. No number from v2's report may be "
            "attributed to it - the denominators differ. Re-measurement is OD-28."
        ),
        "excluded_from_v2": excluded,
        "questions": kept,
    }

    by_category = Counter(q["category"] for q in kept)
    by_reason = Counter(e["classification"] for e in excluded)
    print(f"  v2 queries            {len(spec['questions'])}")
    print(f"  kept in v3            {len(kept)}")
    print(f"  excluded              {len(excluded)}")
    for classification, count in sorted(by_reason.items()):
        print(f"    {classification:<22} {count:3d}")
    print("\n  v3 categories:")
    for category, count in sorted(by_category.items()):
        print(f"    {category:<22} {count:3d}")
    lost = sorted(set(Counter(q["category"] for q in spec["questions"])) - set(by_category))
    if lost:
        print(f"\n  CATEGORIES LOST ENTIRELY: {lost}")

    if args.write:
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        (OUT_DIR / "questions.yaml").write_text(
            HEADER + "\n" + yaml.safe_dump(derived, sort_keys=False, width=100),
            encoding="utf-8",
        )
        print(f"\n  written to {(OUT_DIR / 'questions.yaml').relative_to(REPO)}")
    else:
        print("\n  (dry run; pass --write)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
